import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Playfair_Display, Roboto } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";
import DefaultLayout from "../components/layouts/DefaultLayout";

//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

// const notoSansThai = localFont({
//   src: "../../fonts/NotoSansThai-VariableFont_wdth,wght.ttf",
//   variable: "--font-noto-sans-thai",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} ${playfair.variable} ${roboto.variable} antialiased`}
      >
        <DefaultLayout>
          {children}
        </DefaultLayout>
      </body>

    </html>
  );
}

